site_name: piplexed
site_description: Find outdated pipx installed packages

theme:
  name: 'material'
  palette:
  - media:
    scheme: default
    primary: light blue
    accent: purple
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media:
    scheme: slate
    primary: light blue
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
      - content.code.copy

extra_css:
- css/custom.css